fix: result type generation
tauri-apps/tauri-bindgen pull request #144
Opened 2023-06-03 14:50 UTC by Zercerium

I think this could be a potential fix for https://github.com/tauri-apps/tauri-bindgen/issues/143

2023-06-03 18:04 UTC, JonasKruckenberg approved these changes

2023-06-03 18:04 UTC, JonasKruckenberg commented on crates/gen-js/src/lib.rs
> +                    .map_or("() => {}".to_string(), |ty| "(de) => ".to_string() + &self.print_deserialize_ty(ty));
```suggestion
                    .map_or("() => {}".to_string(), |ty| format!("(de) => {}", self.print_deserialize_ty(ty)));
```

I prefer `format!` for clarity

2023-06-04 05:52 UTC, JonasKruckenberg requested changes

2023-06-04 05:52 UTC, JonasKruckenberg commented on crates/gen-js/src/lib.rs
> +                    .map_or("() => {}".to_string(), |ty| "(de) => ".to_string() + &self.print_deserialize_ty(ty));
Same here btw 😉

2023-06-04 09:34 UTC, Zercerium commented on crates/gen-js/src/lib.rs
> +                    .map_or("() => {}".to_string(), |ty| "(de) => ".to_string() + &self.print_deserialize_ty(ty));
ahh, sry

2023-06-04 11:23 UTC, JonasKruckenberg approved these changes

2023-06-04 13:13 UTC, merged

2023-06-04 13:13 UTC, JonasKruckenberg commented
Thank you!